# Generated by Django 4.0.6 on 2022-10-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Hatchback', 'Hatchback'), ('Combi', 'Combi'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Cabriollet', 'Kabriolet'), ('SUV', 'SUV'), ('Van', 'Van'), ('Pickup', 'Pickup')], max_length=50, null=True, verbose_name='Typ nadwozia'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Pojemność silnika'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Moc silnika'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('PB', 'Benzyna'), ('PB+LPG', 'Benzyna + LPG'), ('ON', 'Diesel'), ('HYB', 'Hybryda'), ('ELE', 'Elektryczny'), ('OTHER', 'Inny')], max_length=50, null=True, verbose_name='Rodzaj silnika'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox_type',
            field=models.CharField(blank=True, choices=[('manual', 'Manualna'), ('automatic', 'Automatyczna'), ('semi-automatic', 'Półautomatyczna')], max_length=50, null=True, verbose_name='Rodzaj skrzyni biegów'),
        ),
    ]
