# Generated by Django 4.0.6 on 2022-11-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_production_year_alter_car_vin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Kod silnika'),
        ),
    ]
