# Generated by Django 4.0.6 on 2022-11-02 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_engine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pojemność silnika'),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970, message='Rok produkcji nie może być mniejszy niż 1970'), django.core.validators.MaxValueValidator(2022, message='Rok produkcji nie może być wyższy niż 2022.')], verbose_name='Rok produkcji'),
        ),
    ]
