# Generated by Django 4.0.6 on 2022-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_engine_capacity_alter_car_engine_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Hatchback', 'Hatchback'), ('Combi', 'Combi'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Kabriolet', 'Kabriolet'), ('SUV', 'SUV'), ('Van', 'Van'), ('Pickup', 'Pickup')], max_length=50, null=True, verbose_name='Typ nadwozia'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox_type',
            field=models.CharField(blank=True, choices=[('Manualna', 'Manualna'), ('Automatyczna', 'Automatyczna'), ('Półautomatyczna', 'Półautomatyczna')], max_length=50, null=True, verbose_name='Rodzaj skrzyni biegów'),
        ),
    ]
