# Generated by Django 4.0.6 on 2022-11-11 11:59

import cars.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_body_type_alter_car_gearbox_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1970, message='Rok produkcji nie może być mniejszy niż 1970'), django.core.validators.MaxValueValidator(2022, message='Rok produkcji nie może być wyższy niż 2022.')], verbose_name='Rok produkcji'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(max_length=17, validators=[cars.validators.validate_vin], verbose_name='Numer VIN'),
        ),
    ]
