# Generated by Django 4.0.6 on 2022-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_brand_alter_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_of_expiry_of_insurance',
            field=models.DateField(null=True, verbose_name='Data ważności ubezpieczenia OC'),
        ),
        migrations.AddField(
            model_name='car',
            name='date_of_expiry_of_technical_inspection',
            field=models.DateField(null=True, verbose_name='Data ważności przeglądu technicznego'),
        ),
    ]
