# Generated by Django 4.0.6 on 2022-12-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(null=True, verbose_name='Godzina'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Oczekujące na akceptację'), (2, 'Zaakceptowane'), (3, 'W trakcie realizacji'), (4, 'Zrealizowane'), (5, 'Odrzucone'), (6, 'Wstrzymane'), (7, 'Oczekiwanie na akceptacje zmian przez klienta'), (8, 'Oczekiwanie na akceptacje zmian przez warsztat')], default=1, verbose_name='Status'),
        ),
    ]
