# Generated by Django 4.0.6 on 2022-12-05 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_date_of_expiry_of_insurance_and_more'),
        ('garages', '0016_alter_garage_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_date_order_time_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garages.garage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
