# Generated by Django 4.0.6 on 2023-01-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_expenditure_car_alter_expenditure_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis problemu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Oczekujące na akceptację'), (2, 'Zaakceptowane - oczekiwanie na pojazd w warsztacie'), (3, 'W trakcie realizacji'), (4, 'Zrealizowane'), (5, 'Odrzucone')], default=1, verbose_name='Status'),
        ),
    ]
