# Generated by Django 4.0.6 on 2022-09-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City/Town'),
        ),
        migrations.AddField(
            model_name='garage',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='garage',
            name='full_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Address'),
        ),
        migrations.AddField(
            model_name='garage',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='garage',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='garage',
            name='street_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Number'),
        ),
    ]
