# Generated by Django 4.0.6 on 2022-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0002_garage_city_garage_country_garage_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Place ID'),
        ),
    ]
