# Generated by Django 4.0.6 on 2022-09-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0003_garage_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='garage',
            name='nip_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='NIP Number'),
        ),
        migrations.AddField(
            model_name='garage',
            name='website_url',
            field=models.URLField(blank=True, max_length=50, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(blank=True, default='test', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garage',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Street Number'),
        ),
    ]
