# Generated by Django 4.0.6 on 2022-10-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0004_garage_description_garage_nip_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='nip_number',
            field=models.BigIntegerField(blank=True, max_length=10, verbose_name='NIP Number'),
        ),
    ]
