# Generated by Django 4.0.6 on 2022-10-26 14:41

from django.db import migrations, models
import garages.validators
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0007_alter_garage_country_alter_garage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='full_address',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[garages.validators.validate_poland_country], verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[main.validators.validate_special_characters_and_numbers], verbose_name='Name'),
        ),
    ]
