# Generated by Django 4.0.6 on 2022-11-24 11:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import garages.validators
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0011_alter_garage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='full_address',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[garages.validators.validate_poland_country], verbose_name='Pełny adres'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Warsztat aktywny'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[main.validators.validate_special_characters_and_numbers], verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='nip_number',
            field=models.BigIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999, message='Niepoprawny numer NIP'), django.core.validators.MinValueValidator(1000000000, message='Niepoprawny numer NIP')], verbose_name='Numer NIP'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID miejsca'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numer budynku'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='website_url',
            field=models.URLField(blank=True, max_length=50, verbose_name='Adres URL'),
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanical_repairs', models.BooleanField(default=False, verbose_name='Naprawy mechaniczne')),
                ('electrical_repairs', models.BooleanField(default=False, verbose_name='Naprawy elektryczne')),
                ('chassis_maintenance', models.BooleanField(default=False, verbose_name='Konserwacja podwozia')),
                ('tire_vulcanization_and_replacement', models.BooleanField(default=False, verbose_name='Wulkanizacja i wymiana opon')),
                ('air_conditioning_repair_and_cleaning', models.BooleanField(default=False, verbose_name='Naprawa i czyszczenie klimatyzacji')),
                ('lpg_installations_and_periodic_inspections', models.BooleanField(default=False, verbose_name='Instalacje LPG i okresowe przeglądy')),
                ('bodywork_and_paint_repairs', models.BooleanField(default=False, verbose_name='Naprawy blacharsko-lakiernicze')),
                ('window_replacement', models.BooleanField(default=False, verbose_name='Wymiana szyb')),
                ('inspections', models.BooleanField(default=False, verbose_name='Przeglądy')),
                ('car_tuning_and_sports_modifications', models.BooleanField(default=False, verbose_name='Tuning i sportowe modyfikacje')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garages.garage')),
            ],
        ),
    ]
