# Generated by Django 4.0.6 on 2022-11-26 21:53

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0012_alter_garage_city_alter_garage_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[main.validators.validate_special_characters_and_numbers], verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='servicelist',
            name='air_conditioning_repair_and_cleaning',
            field=models.BooleanField(default=False, verbose_name='Serwis klimatyzacji'),
        ),
        migrations.AlterField(
            model_name='servicelist',
            name='lpg_installations_and_periodic_inspections',
            field=models.BooleanField(default=False, verbose_name='Instalacje LPG'),
        ),
        migrations.AlterField(
            model_name='servicelist',
            name='tire_vulcanization_and_replacement',
            field=models.BooleanField(default=False, verbose_name='Wulkanizacja'),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garages.garage')),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'unique_together': {('weekday', 'from_hour', 'to_hour')},
            },
        ),
    ]
