# Generated by Django 4.0.6 on 2022-11-28 08:17

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0013_alter_garage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[main.validators.validate_special_characters_and_numbers], verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
