# Generated by Django 4.0.6 on 2022-12-30 16:26

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0016_alter_garage_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[main.validators.validate_special_characters_and_numbers], verbose_name='Nazwa'),
        ),
    ]
