# Generated by Django 4.0.6 on 2023-02-12 16:54

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0017_alter_openinghours_unique_together_alter_garage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[main.validators.validate_special_characters_and_numbers], verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID miejsca'),
        ),
    ]
